(function(){
  var modules=[
    ['ACTIVITÉ',[['dashboardSection','Tableau de bord'],['searchSection','Locations'],['planningSection','Planning'],['deliveriesSection','Livraisons']]],
    ['DOCUMENTS',[['contracts','Contrats','/contrat?view=list'],['inspectionsSection','États des lieux'],['depositsSection','Dépôts de garantie']]],
    ['COMMERCIAL',[['quoteSection','Devis express']]],
    ['GESTION',[['vehiclesSection','Véhicules'],['statisticsSection','Statistiques'],['settingsSection','Paramètres']]]
  ];
  function labelFor(id){ var contextual={clientFormSection:'Locations',clientSheetSection:'Locations',rentalFormSection:'Locations',rentalDetailSection:'Locations'}; if(contextual[id])return contextual[id]; for(var g=0;g<modules.length;g++) for(var i=0;i<modules[g][1].length;i++) if(modules[g][1][i][0]===id) return modules[g][1][i][1]; return 'Tableau de bord'; }
  function navHtml(active){ return modules.map(function(group){ return '<div class="bo-nav-group"><p class="bo-nav-group-title">'+group[0]+'</p>'+group[1].map(function(item){ var href=item[2]; return href?'<a class="btn btn-sm '+(active===item[0]?'is-active':'')+'" href="'+href+'">'+item[1]+'</a>':'<button type="button" class="btn btn-sm '+(active===item[0]?'is-active':'')+'" data-bo-section="'+item[0]+'">'+item[1]+'</button>'; }).join('')+'</div>'; }).join(''); }
  function emit(section){ document.dispatchEvent(new CustomEvent('getlocation:backoffice-navigate',{detail:{section:section}})); }
  function mountHeader(title, onBack){
    var old=document.getElementById('boMobileHeader'); if(old) old.remove();
    var header=document.createElement('header'); header.id='boMobileHeader'; header.className='bo-mobile-header'; header.innerHTML='<button class="bo-back-btn" type="button">‹ Retour</button><h1></h1><button class="bo-menu-trigger" type="button">☰ Menu</button>';
    header.querySelector('h1').textContent=title; var back=header.querySelector('.bo-back-btn'); if(onBack){back.classList.add('is-visible');back.onclick=onBack;} document.body.insertBefore(header,document.body.firstChild); return header;
  }
  function initBackoffice(active){
    document.body.classList.add('bo-shell-active'); var sidebar=document.getElementById('internalSidebar'); if(!sidebar) return;
    sidebar.innerHTML='<p class="sidebar-title">GET LOCATION</p><nav class="internal-nav" id="boSharedNav">'+navHtml(active)+'</nav><button type="button" class="btn btn-sm" id="boSharedLogout">Se déconnecter</button>';
    function menu(open){ sidebar.classList.toggle('is-open',open); var b=document.getElementById('sidebarBackdrop');if(b)b.classList.toggle('is-open',open); }
    sidebar.querySelectorAll('[data-bo-section]').forEach(function(button){button.onclick=function(){emit(button.dataset.boSection);menu(false);};});
    sidebar.querySelector('#boSharedLogout').onclick=function(){var b=document.getElementById('logoutBtn');if(b)b.click();};
    var header=mountHeader(labelFor(active),active!=='dashboardSection'?function(){emit('dashboardSection');}:null); header.querySelector('.bo-menu-trigger').onclick=function(){menu(true);};
    var bottom=document.createElement('nav');bottom.className='bo-bottom-nav';bottom.id='boBottomNav';bottom.innerHTML='<button data-bo-section="dashboardSection">Accueil</button><button data-bo-section="searchSection">Locations</button><button data-bo-section="planningSection">Planning</button><button data-bo-menu>Menu</button>';document.body.appendChild(bottom);bottom.querySelectorAll('[data-bo-section]').forEach(function(b){b.onclick=function(){emit(b.dataset.boSection);};});bottom.querySelector('[data-bo-menu]').onclick=function(){menu(true);};
  }
  function setActive(section){ document.querySelectorAll('[data-bo-section]').forEach(function(el){el.classList.toggle('is-active',el.dataset.boSection===section);});var h=document.querySelector('#boMobileHeader h1');if(h)h.textContent=labelFor(section);var back=document.querySelector('#boMobileHeader .bo-back-btn');if(back){var previous=['clientFormSection','clientSheetSection','rentalFormSection','rentalDetailSection'].includes(section)?'searchSection':'dashboardSection';back.classList.toggle('is-visible',section!=='dashboardSection');back.onclick=function(){emit(previous);};} }
  function initContracts(){ document.body.classList.add('bo-shell-active'); var owner=document.getElementById('ownerView');if(!owner||document.querySelector('.bo-desktop-contract-nav'))return;var box=document.createElement('div');box.className='bo-desktop-contract-nav';box.innerHTML='<button class="bo-menu-trigger" type="button">☰ Menu</button><aside class="bo-contract-drawer" hidden>'+navHtml('contracts')+'<button type="button" class="btn btn-sm" data-bo-contract-logout>Se déconnecter</button></aside>';document.body.appendChild(box);var drawer=box.querySelector('aside');function toggle(){drawer.hidden=!drawer.hidden;}box.querySelector('.bo-menu-trigger').onclick=toggle;drawer.querySelectorAll('[data-bo-section]').forEach(function(button){button.onclick=function(){window.location.href='/back-office#'+({dashboardSection:'dashboard',searchSection:'locations',planningSection:'planning',deliveriesSection:'livraisons',quoteSection:'devis',inspectionsSection:'edl',depositsSection:'deposits',vehiclesSection:'vehicules',statisticsSection:'statistiques',settingsSection:'parametres'}[button.dataset.boSection]||'dashboard');};});box.querySelector('[data-bo-contract-logout]').onclick=function(){document.getElementById('agencyLogoutBtn').click();};var header=mountHeader('Contrats',function(){window.location.href='/back-office#dashboard';});header.querySelector('.bo-menu-trigger').onclick=toggle;var bottom=document.createElement('nav');bottom.className='bo-bottom-nav';bottom.innerHTML='<button data-bo-link="/back-office#dashboard">Accueil</button><button data-bo-link="/back-office#locations">Locations</button><button data-bo-link="/back-office#planning">Planning</button><button data-bo-menu>Menu</button>';document.body.appendChild(bottom);bottom.querySelectorAll('[data-bo-link]').forEach(function(b){b.onclick=function(){window.location.href=b.dataset.boLink;};});bottom.querySelector('[data-bo-menu]').onclick=toggle; }
  window.GETLOCATION_BACKOFFICE={initBackoffice:initBackoffice,setActive:setActive,initContracts:initContracts};
})();
